### ISSUE TITLE
Confirming implementation dates&times

### ISSUE THREAD

**Issue by EmilHafeez** [Brian-Elbel-s-Research-Projects/project-overview#10]
Follow-up from Wednesday 4/13/22 ML meeting, just confirming these are correct

https://github.com/Brian-Elbel-s-Research-Projects/menu-labeling-impact-on-calories-drive-through/issues/1

**Comment by lloydheng** [comment]
Checked with Courtney yesterday, and she was surprised seeing MA/CA/OR in it (I left them in, but made the caveat in note below). 

Other than MA/CA/OR being on that 'implemented' table, the other implemented locations are correct and the dates were retrieved from the legislation excel table (which I assume is correct, or our best guess of the implementation dates).

**NOTE:** CA implemented labelling partially (in-store only, at the specified implementation date). MA/OR never did so until the national rollout in 2017.

**Comment by EmilHafeez** [comment]
Noted. I have removed MA and OR from receiving a policy label, entry time, and a treatment==1 assignment then.
