### ISSUE TITLE
chart for how different projects differ analytically

### ISSUE THREAD

**Issue by EmilHafeez** [Brian-Elbel-s-Research-Projects/project-overview#29]
re Pasquale comment in 6/24/22 meeting
I can start infrastructure

**Comment by eriliawu** [comment]
| | ML drive-thru | ML in-store| ML in CA | ML legislation vs. implementation |
| ---- | ---- | ---- | ---- | ---- |
| Analyst | Lloyd | Emil | Kriti | Pedro |
| Data | Drive-thru data from Suffolk, Vermont, King, Schenectady | In-store data from California, Suffolk, Vermont, King, Schenectady, Montgomery | All data from California | Drive-thru data from Albany, California, Maine, Massachusetts, Oregon (legislation), and Suffolk, Vermont, King, Schenectady, Montgomery (implementation)
| Method | synthetic control | matching+weighting w/ pre-match | using same-store drive-thru as comparison | matching+weighting w/ pre-match |
| Main estimate| | | | |

**Comment by EmilHafeez** [comment]
Should we share this with Pasquale/merge it with what he wants? Could this issue be resolved?

**Comment by eriliawu** [comment]
This GitHub lab account is private so Pasquale doesn't have access to this... we didn't think of that when we started this. We could just follow what Pasquale started, and the downside is that it's emails flying around, and not great for version control. Open to ideas.

**Comment by EmilHafeez** [comment]
Honestly I think either a) we keep this just for our own documentation, b) add the main estimates with and without beverages to his table and then scrap this table, or c) just scrap this table? Completely agree about the version control but he seems okay with it based on his existing table email

**Comment by EmilHafeez** [comment]
Re: Analyst meeting 8/15/22, considered closed. Projects have differed substantively and recent ML meetings have clarified to faculty, e.g. see 8/10/22 slides.
