### ISSUE TITLE
Understanding fixed effect vs. random effect

### ISSUE THREAD

**Issue by eriliawu** [Brian-Elbel-s-Research-Projects/project-overview#31]
From previous discussions, we could probably all use a refresher on this topic. Perhaps we could all do some reading on this, and one of us could do a little deep dive on this and present to the team? There's a deadline. Just throwing out an idea.

A helpful post to get started [here](https://stats.stackexchange.com/questions/4700/what-is-the-difference-between-fixed-effect-random-effect-and-mixed-effect-mode).

**Comment by EmilHafeez** [comment]
redundant with internal learning plan, so closing for now!
