### ISSUE TITLE
Colors 🌈

### ISSUE THREAD

**Issue by lloydheng** [Brian-Elbel-s-Research-Projects/project-overview#61]

**Comment by EmilHafeez** [comment]
@lloydheng Can you point me to the documentation you produced? Making a histogram right now and was thinking of using your research on these!

**Comment by lloydheng** [comment]
https://nyulangone-my.sharepoint.com/:u:/g/personal/lloyd_heng_nyulangone_org/ETgfU-2LsvJMoqUH4Pp8DroBwzqzV2Fo-Jvl-18NP2fn_Q?e=xH54c8

We're using the last scheme, titled "L".
