### ISSUE TITLE
Clustering SE and robust SE in `plm` library

### ISSUE THREAD

**Issue by eriliawu** [Brian-Elbel-s-Research-Projects/project-overview#65]

**Comment by EmilHafeez** [comment]
I believe this can be closed until peer review for Paper 1 returns comments; discussion involved shifting to felm or similar package

Problem is that the commands to extract robust SEs from the plm.object do not support weighted plm's, which we of course use. Lloyd has a tentative workaround using an lm.object instead, though discussion also considered converting to felm() or similar

**Comment by eriliawu** [comment]
Implementing fixed effects and clustered standard errors with weights is possible with `lfe` library, with `felm` function.

See link [here](https://stats.stackexchange.com/questions/379575/r-robust-standard-errors-in-panel-regression-clustered-at-level-group-fixed).

As the link above explained, the code is loosely like this:
`felm(y ~x1 + x2 | fixedeffect1 + fixedeffect2 | Ivvariable | clustervar1 + clustervar2, data = data)`
Replace a section with 0 if it's not necessary.

In the `felm` [documentation](https://cran.r-project.org/web/packages/lfe/lfe.pdf), `weights` is an option.

**Comment by EmilHafeez** [comment]
Marking this as closed and as reference for when/if the Paper 1 (or any current implementations) require it

**Comment by lloydheng** [comment]
Second comment by Grant [here](https://stats.stackexchange.com/questions/389393/r-confused-about-robust-standard-errors-using-felm-and-huxreg) compares the output from `msummary` of an `felm` object specifying `robust`, and the output from an `lm` object passed through `coeftest`. They are identical.
