### ISSUE TITLE
internal learning platform

### ISSUE THREAD

**Issue by eriliawu** [Brian-Elbel-s-Research-Projects/project-overview#69]
What makes the most sense in terms of keeping a record of all the learning materials?

Repo [here](https://github.com/Brian-Elbel-s-Research-Projects/internal-learning).

**Comment by EmilHafeez** [comment]
So far this seems to be working?

**Comment by EmilHafeez** [comment]
@Brian-Elbel-s-Research-Projects/analytical-team I'm closing this issue but please refer to it via the `is:issue is:open` filter
