### ISSUE TITLE
Aggregating ACS variables in SC production

### ISSUE THREAD

**Issue by EmilHafeez** [Brian-Elbel-s-Research-Projects/project-overview#81]
Excluded?

**Comment by EmilHafeez** [comment]
CC aggregates ACS variables by (ACS*unit weight) then sums, as though time-varying

**Comment by eriliawu** [comment]
For regressions in general, no need to aggregate ACS characteristics as they are not used in the regressions (restaurant FE).

For community characteristics related analysis, ACS variables for control restaurants are aggregated as they are for other time varying variables.
